// tokens.json in the W3C DTCG Format Module 2025.10 + Color Module 2025.10 (docs/CONTRACTS.md §2).
// Pure: ProjectFile → text. Reads `resolved` only and is stack-agnostic.
import { COLOR_ROLES, FONT_SIZE_KEYS, SPACE_KEYS, type FontRef, type ProjectFile, type Resolved } from "@/contracts/project";
import { hexToRgb } from "@/domain/color/hex";
import { assertExportable } from "@/domain/decisions";
import { stableJson } from "@/lib/stable-json";

export const NS = "com.github.mikkelstaehr.design-wizard";

export interface ColorToken {
  $type: "color";
  $value: { colorSpace: "srgb"; components: [number, number, number]; alpha: 1; hex: string };
}
export interface DimensionToken {
  $type: "dimension";
  $value: { value: number; unit: "px" | "rem" };
}
export interface FontFamilyToken {
  $type: "fontFamily";
  $value: [string, string];
  $extensions: { [NS]: Omit<FontRef, "family" | "generic"> };
}
export interface NumberToken {
  $type: "number";
  $value: number;
}

export interface Tokens {
  $description: string;
  $extensions: { [NS]: { schemaVersion: 1; project: string; theme: "light" } };
  color: Record<string, ColorToken>;
  font: { display: FontFamilyToken; text: FontFamilyToken };
  "font-size": Record<string, DimensionToken>;
  "line-height": { text: NumberToken; display: NumberToken };
  radius: { base: DimensionToken };
  space: Record<string, DimensionToken>;
}

const round4 = (n: number) => Math.round(n * 10000) / 10000;

function color(hex: string): ColorToken {
  const [r, g, b] = hexToRgb(hex).map((c) => round4(c / 255)) as [number, number, number];
  return { $type: "color", $value: { colorSpace: "srgb", components: [r, g, b], alpha: 1, hex } };
}

const dim = (value: number, unit: "px" | "rem"): DimensionToken => ({ $type: "dimension", $value: { value, unit } });

function font(f: FontRef): FontFamilyToken {
  const { catalogueId, fontsource, weights, style, subset, license, copyright } = f;
  return {
    $type: "fontFamily",
    $value: [f.family, f.generic],
    $extensions: { [NS]: { catalogueId, fontsource, weights: [...weights], style, subset, license, copyright } },
  };
}

/** Runs the export gate (domain/decisions.ts), then returns the snapshot and the project name. */
export function requireResolved(p: ProjectFile): Resolved & { name: string } {
  assertExportable(p);
  return { ...p.resolved, name: p.profile.name };
}

export function buildTokens(p: ProjectFile): Tokens {
  const r = requireResolved(p);
  const out: Tokens = {
    $description: `Design tokens for ${r.name}. Generated by Design Wizard.`,
    $extensions: { [NS]: { schemaVersion: 1, project: r.name, theme: "light" } },
    color: {},
    font: { display: font(r.font.display), text: font(r.font.text) },
    "font-size": {},
    "line-height": { text: { $type: "number", $value: r.lineHeight.text }, display: { $type: "number", $value: r.lineHeight.display } },
    radius: { base: dim(r.radius, "px") },
    space: {},
  };
  for (const role of COLOR_ROLES) out.color[role] = color(r.color.light[role]);
  for (const k of FONT_SIZE_KEYS) out["font-size"][k] = dim(r.fontSize[k], "rem");
  for (const k of SPACE_KEYS) out.space[k] = dim(r.space[k], "px");
  return out;
}

export function tokensJson(p: ProjectFile): string {
  return stableJson(buildTokens(p));
}
